services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "server.py"]
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
    expose:
      - "8000"

  agent:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "agent.py", "start"]
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
    depends_on:
      - web