services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx # これは前回作成したものでOK
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - voice-agent

  voice-agent:
    build:
      context: .
      dockerfile: Dockerfile # メインのDockerfile
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
    # ports はnginxが担当するので不要